// <auto-generated />
using System;
using DigitalRegistry.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigitalRegistry.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigitalRegistry.Models.Agencies", b =>
                {
                    b.Property<int>("agencies_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Social_Mediaid");

                    b.Property<string>("info_url");

                    b.Property<string>("name");

                    b.HasKey("agencies_id");

                    b.HasIndex("Social_Mediaid");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("DigitalRegistry.Models.All_Social_Media", b =>
                {
                    b.Property<int>("page")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("count_");

                    b.Property<int>("page_size");

                    b.Property<int>("pages");

                    b.HasKey("page");

                    b.ToTable("AllSocialMedia");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Social_Media", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("All_Social_Mediapage");

                    b.Property<string>("account");

                    b.Property<string>("created_at");

                    b.Property<string>("language");

                    b.Property<string>("long_description");

                    b.Property<string>("organization");

                    b.Property<string>("service_display_name");

                    b.Property<string>("service_key");

                    b.Property<string>("service_url");

                    b.Property<string>("short_description");

                    b.Property<string>("updated_at");

                    b.HasKey("id");

                    b.HasIndex("All_Social_Mediapage");

                    b.ToTable("Social_Media");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Tags", b =>
                {
                    b.Property<int>("tags_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Social_Mediaid");

                    b.Property<string>("tag_text");

                    b.HasKey("tags_id");

                    b.HasIndex("Social_Mediaid");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Agencies", b =>
                {
                    b.HasOne("DigitalRegistry.Models.Social_Media")
                        .WithMany("agencies")
                        .HasForeignKey("Social_Mediaid");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Social_Media", b =>
                {
                    b.HasOne("DigitalRegistry.Models.All_Social_Media")
                        .WithMany("results")
                        .HasForeignKey("All_Social_Mediapage");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Tags", b =>
                {
                    b.HasOne("DigitalRegistry.Models.Social_Media")
                        .WithMany("tags")
                        .HasForeignKey("Social_Mediaid");
                });
#pragma warning restore 612, 618
        }
    }
}
