// <auto-generated />
using System;
using DigitalRegistry.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigitalRegistry.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigitalRegistry.Models.Agencies", b =>
                {
                    b.Property<int>("a_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Info_url");

                    b.Property<string>("Name");

                    b.Property<int?>("Social_MediaId");

                    b.HasKey("a_id");

                    b.HasIndex("Social_MediaId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("DigitalRegistry.Models.All_Social_Media", b =>
                {
                    b.Property<int>("page")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("count_");

                    b.Property<int>("page_size");

                    b.Property<int>("pages");

                    b.HasKey("page");

                    b.ToTable("All_Social_Media");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Social_Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account");

                    b.Property<int?>("All_Social_Mediapage");

                    b.Property<string>("Created_at");

                    b.Property<string>("Language");

                    b.Property<string>("Long_description");

                    b.Property<string>("Organization");

                    b.Property<string>("Service_display_name");

                    b.Property<string>("Service_key");

                    b.Property<string>("Service_url");

                    b.Property<string>("Short_description");

                    b.Property<string>("Updated_at");

                    b.HasKey("Id");

                    b.HasIndex("All_Social_Mediapage");

                    b.ToTable("Social_Media");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Tags", b =>
                {
                    b.Property<int>("t_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Social_MediaId");

                    b.Property<string>("Tag_text");

                    b.HasKey("t_id");

                    b.HasIndex("Social_MediaId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Agencies", b =>
                {
                    b.HasOne("DigitalRegistry.Models.Social_Media")
                        .WithMany("agencies")
                        .HasForeignKey("Social_MediaId");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Social_Media", b =>
                {
                    b.HasOne("DigitalRegistry.Models.All_Social_Media")
                        .WithMany("Results")
                        .HasForeignKey("All_Social_Mediapage");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Tags", b =>
                {
                    b.HasOne("DigitalRegistry.Models.Social_Media")
                        .WithMany("tags")
                        .HasForeignKey("Social_MediaId");
                });
#pragma warning restore 612, 618
        }
    }
}
